schema_version = "1.0.0"
id = "vfx"
version = "1.0.0"
name = "CArtz VFX Effects"
tagline = "All of CArtz Blender VFX Effects"
maintainer = "CArtz"
type = "add-on"
blender_version_min = "4.2.0"
license = ["GPL-3.0-or-later"]
